# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ali Aliev
tagline:          'Python, Django, PostgreSQL'
url:              http://aliev.me
shorturl:         aliev.me

author:
  name:           'Ali Aliev'
  url:            https://twitter.com/ali_aliev

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/aliev/aliev.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
