# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
  
# Site settings
title: "Ali Aliev"
description: > # this means to ignore newlines until "email:"
   Programming, Music, Life

email: ali@aliev.me
#blog logo
logo: "https://s.gravatar.com/avatar/0c599bcadc37adf2e64ad7e33cf5464b?s=100"
# blog cover
cover: "/assets/images/img.jpg"

name: 'Ali Aliev'
author: 'Ali Aliev'
author_image: "http://s.gravatar.com/avatar/0c599bcadc37adf2e64ad7e33cf5464b?s=80"

paginate:	5

url: "http://aliev.me" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ali_aliev
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/alievali
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/aliev
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/u/0/+alialievaliev/
    desc:	Add me on google+
    share_url: https://plus.google.com/share
    share_link: "&amp;url="
    share_title: ?title=
