# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ali Aliev blog
tagline:             "Python, Django, PostgreSQL"
url:                 http://aliev.me
paginate:            5
baseurl:             "http://aliev.me"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ali Aliev
  url:               https://twitter.com/ali_aliev
  email:             shamkir@gmail.com
  google_plus:       https://plus.google.com/u/0/106445062387931379068

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/aliev

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
